% This file is based on the "definegars.m" generated by matlab.
% It offers common interface definitions of current native library.
% You can change this file according to the "definegars.m" generated by you if needed.


function libDef = library_definition()

libDef = clibgen.LibraryDefinition("garsData.xml");

libDef.OutputFolder = ".";
libDef.Libraries = "../bin/GaRS.lib";


MultilookfDefinition = addFunction(libDef, ...
   "int Multilookf(int inRows,int inCols,float const * input,int rowLook,int colLook,int outRows,int outCols,float * output)", ...
   "MATLABName", "clib.gars.Multilookf", ...
   "Description", "clib.gars.Multilookf Representation of C++ function Multilookf.");
defineArgument(MultilookfDefinition, "inRows", "int32");
defineArgument(MultilookfDefinition, "inCols", "int32");
defineArgument(MultilookfDefinition, "input", "single", "input", ["inRows" "inCols"]);
defineArgument(MultilookfDefinition, "rowLook", "int32");
defineArgument(MultilookfDefinition, "colLook", "int32");
defineArgument(MultilookfDefinition, "outRows", "int32");
defineArgument(MultilookfDefinition, "outCols", "int32");
defineArgument(MultilookfDefinition, "output", "single", "output", ["outRows" "outCols"]);
defineOutput(MultilookfDefinition, "RetVal", "int32");
validate(MultilookfDefinition);


MultilookdDefinition = addFunction(libDef, ...
   "int Multilookd(int inRows,int inCols,double const * input,int rowLook,int colLook,int outRows,int outCols,double * output)", ...
   "MATLABName", "clib.gars.Multilookd", ...
   "Description", "clib.gars.Multilookd Representation of C++ function Multilookd.");
defineArgument(MultilookdDefinition, "inRows", "int32");
defineArgument(MultilookdDefinition, "inCols", "int32");
defineArgument(MultilookdDefinition, "input", "double", "input", ["inRows" "inCols"]);
defineArgument(MultilookdDefinition, "rowLook", "int32");
defineArgument(MultilookdDefinition, "colLook", "int32");
defineArgument(MultilookdDefinition, "outRows", "int32");
defineArgument(MultilookdDefinition, "outCols", "int32");
defineArgument(MultilookdDefinition, "output", "double", "output", ["outRows" "outCols"]);
defineOutput(MultilookdDefinition, "RetVal", "int32");
validate(MultilookdDefinition);


RefinedLeeFilting3fDefinition = addFunction(libDef, ...
   "int RefinedLeeFilting3f(int lookNum,int rows,int cols,float const * c11,float const * c22,float const * c33,float const * c12r,float const * c13r,float const * c23r,float const * c12i,float const * c13i,float const * c23i,float * outC11,float * outC22,float * outC33,float * outC12r,float * outC13r,float * outC23r,float * outC12i,float * outC13i,float * outC23i)", ...
   "MATLABName", "clib.gars.RefinedLeeFilting3f", ...
   "Description", "clib.gars.RefinedLeeFilting3f Representation of C++ function RefinedLeeFilting3f.");
defineArgument(RefinedLeeFilting3fDefinition, "lookNum", "int32");
defineArgument(RefinedLeeFilting3fDefinition, "rows", "int32");
defineArgument(RefinedLeeFilting3fDefinition, "cols", "int32");
defineArgument(RefinedLeeFilting3fDefinition, "c11", "single", "input", ["rows" "cols"]); 
defineArgument(RefinedLeeFilting3fDefinition, "c22", "single", "input", ["rows" "cols"]); 
defineArgument(RefinedLeeFilting3fDefinition, "c33", "single", "input", ["rows" "cols"]);
defineArgument(RefinedLeeFilting3fDefinition, "c12r", "single", "input", ["rows" "cols"]);
defineArgument(RefinedLeeFilting3fDefinition, "c13r", "single", "input", ["rows" "cols"]); 
defineArgument(RefinedLeeFilting3fDefinition, "c23r", "single", "input", ["rows" "cols"]); 
defineArgument(RefinedLeeFilting3fDefinition, "c12i", "single", "input", ["rows" "cols"]); 
defineArgument(RefinedLeeFilting3fDefinition, "c13i", "single", "input", ["rows" "cols"]); 
defineArgument(RefinedLeeFilting3fDefinition, "c23i", "single", "input", ["rows" "cols"]); 
defineArgument(RefinedLeeFilting3fDefinition, "outC11", "single", "output", ["rows" "cols"]); 
defineArgument(RefinedLeeFilting3fDefinition, "outC22", "single", "output", ["rows" "cols"]); 
defineArgument(RefinedLeeFilting3fDefinition, "outC33", "single", "output", ["rows" "cols"]); 
defineArgument(RefinedLeeFilting3fDefinition, "outC12r", "single", "output", ["rows" "cols"]); 
defineArgument(RefinedLeeFilting3fDefinition, "outC13r", "single", "output", ["rows" "cols"]); 
defineArgument(RefinedLeeFilting3fDefinition, "outC23r", "single", "output", ["rows" "cols"]); 
defineArgument(RefinedLeeFilting3fDefinition, "outC12i", "single", "output", ["rows" "cols"]); 
defineArgument(RefinedLeeFilting3fDefinition, "outC13i", "single", "output", ["rows" "cols"]); 
defineArgument(RefinedLeeFilting3fDefinition, "outC23i", "single", "output", ["rows" "cols"]); 
defineOutput(RefinedLeeFilting3fDefinition, "RetVal", "int32");
validate(RefinedLeeFilting3fDefinition);


RefinedLeeFilting3dDefinition = addFunction(libDef, ...
   "int RefinedLeeFilting3d(int lookNum,int rows,int cols,double const * c11,double const * c22,double const * c33,double const * c12r,double const * c13r,double const * c23r,double const * c12i,double const * c13i,double const * c23i,double * outC11,double * outC22,double * outC33,double * outC12r,double * outC13r,double * outC23r,double * outC12i,double * outC13i,double * outC23i)", ...
   "MATLABName", "clib.gars.RefinedLeeFilting3d", ...
   "Description", "clib.gars.RefinedLeeFilting3d Representation of C++ function RefinedLeeFilting3d.");
defineArgument(RefinedLeeFilting3dDefinition, "lookNum", "int32");
defineArgument(RefinedLeeFilting3dDefinition, "rows", "int32");
defineArgument(RefinedLeeFilting3dDefinition, "cols", "int32");
defineArgument(RefinedLeeFilting3dDefinition, "c11", "double", "input", ["rows" "cols"]);
defineArgument(RefinedLeeFilting3dDefinition, "c22", "double", "input", ["rows" "cols"]);
defineArgument(RefinedLeeFilting3dDefinition, "c33", "double", "input", ["rows" "cols"]);
defineArgument(RefinedLeeFilting3dDefinition, "c12r", "double", "input", ["rows" "cols"]);
defineArgument(RefinedLeeFilting3dDefinition, "c13r", "double", "input", ["rows" "cols"]);
defineArgument(RefinedLeeFilting3dDefinition, "c23r", "double", "input", ["rows" "cols"]);
defineArgument(RefinedLeeFilting3dDefinition, "c12i", "double", "input", ["rows" "cols"]);
defineArgument(RefinedLeeFilting3dDefinition, "c13i", "double", "input", ["rows" "cols"]);
defineArgument(RefinedLeeFilting3dDefinition, "c23i", "double", "input", ["rows" "cols"]);
defineArgument(RefinedLeeFilting3dDefinition, "outC11", "double", "output", ["rows" "cols"]);
defineArgument(RefinedLeeFilting3dDefinition, "outC22", "double", "output", ["rows" "cols"]);
defineArgument(RefinedLeeFilting3dDefinition, "outC33", "double", "output", ["rows" "cols"]);
defineArgument(RefinedLeeFilting3dDefinition, "outC12r", "double", "output", ["rows" "cols"]);
defineArgument(RefinedLeeFilting3dDefinition, "outC13r", "double", "output", ["rows" "cols"]);
defineArgument(RefinedLeeFilting3dDefinition, "outC23r", "double", "output", ["rows" "cols"]);
defineArgument(RefinedLeeFilting3dDefinition, "outC12i", "double", "output", ["rows" "cols"]);
defineArgument(RefinedLeeFilting3dDefinition, "outC13i", "double", "output", ["rows" "cols"]);
defineArgument(RefinedLeeFilting3dDefinition, "outC23i", "double", "output", ["rows" "cols"]);
defineOutput(RefinedLeeFilting3dDefinition, "RetVal", "int32");
validate(RefinedLeeFilting3dDefinition);


RefinedLeeFilting2fDefinition = addFunction(libDef, ...
   "int RefinedLeeFilting2f(int lookNum,int rows,int cols,float const * c11,float const * c22,float const * c12r,float const * c12i,float * outC11,float * outC22,float * outC12r,float * outC12i)", ...
   "MATLABName", "clib.gars.RefinedLeeFilting2f", ...
   "Description", "clib.gars.RefinedLeeFilting2f Representation of C++ function RefinedLeeFilting2f.");
defineArgument(RefinedLeeFilting2fDefinition, "lookNum", "int32");
defineArgument(RefinedLeeFilting2fDefinition, "rows", "int32");
defineArgument(RefinedLeeFilting2fDefinition, "cols", "int32");
defineArgument(RefinedLeeFilting2fDefinition, "c11", "single", "input", ["rows" "cols"]); 
defineArgument(RefinedLeeFilting2fDefinition, "c22", "single", "input", ["rows" "cols"]); 
defineArgument(RefinedLeeFilting2fDefinition, "c12r", "single", "input", ["rows" "cols"]); 
defineArgument(RefinedLeeFilting2fDefinition, "c12i", "single", "input", ["rows" "cols"]); 
defineArgument(RefinedLeeFilting2fDefinition, "outC11", "single", "output", ["rows" "cols"]); 
defineArgument(RefinedLeeFilting2fDefinition, "outC22", "single", "output", ["rows" "cols"]); 
defineArgument(RefinedLeeFilting2fDefinition, "outC12r", "single", "output", ["rows" "cols"]); 
defineArgument(RefinedLeeFilting2fDefinition, "outC12i", "single", "output", ["rows" "cols"]); 
defineOutput(RefinedLeeFilting2fDefinition, "RetVal", "int32");
validate(RefinedLeeFilting2fDefinition);


RefinedLeeFilting2dDefinition = addFunction(libDef, ...
   "int RefinedLeeFilting2d(int lookNum,int rows,int cols,double const * c11,double const * c22,double const * c12r,double const * c12i,double * outC11,double * outC22,double * outC12r,double * outC12i)", ...
   "MATLABName", "clib.gars.RefinedLeeFilting2d", ...
   "Description", "clib.gars.RefinedLeeFilting2d Representation of C++ function RefinedLeeFilting2d.");
defineArgument(RefinedLeeFilting2dDefinition, "lookNum", "int32");
defineArgument(RefinedLeeFilting2dDefinition, "rows", "int32");
defineArgument(RefinedLeeFilting2dDefinition, "cols", "int32");
defineArgument(RefinedLeeFilting2dDefinition, "c11", "double", "input", ["rows" "cols"]);
defineArgument(RefinedLeeFilting2dDefinition, "c22", "double", "input", ["rows" "cols"]);
defineArgument(RefinedLeeFilting2dDefinition, "c12r", "double", "input", ["rows" "cols"]);
defineArgument(RefinedLeeFilting2dDefinition, "c12i", "double", "input", ["rows" "cols"]);
defineArgument(RefinedLeeFilting2dDefinition, "outC11", "double", "output", ["rows" "cols"]);
defineArgument(RefinedLeeFilting2dDefinition, "outC22", "double", "output", ["rows" "cols"]);
defineArgument(RefinedLeeFilting2dDefinition, "outC12r", "double", "output", ["rows" "cols"]);
defineArgument(RefinedLeeFilting2dDefinition, "outC12i", "double", "output", ["rows" "cols"]);
defineOutput(RefinedLeeFilting2dDefinition, "RetVal", "int32");
validate(RefinedLeeFilting2dDefinition);


CloudePottier3fDefinition = addFunction(libDef, ...
   "void CloudePottier3f(int rows,int cols,float const * t11,float const * t22,float const * t33,float const * t12r,float const * t13r,float const * t23r,float const * t12i,float const * t13i,float const * t23i,float * outH,float * outAlpha,float * outA)", ...
   "MATLABName", "clib.gars.CloudePottier3f", ...
   "Description", "clib.gars.CloudePottier3f Representation of C++ function CloudePottier3f.");
defineArgument(CloudePottier3fDefinition, "rows", "int32");
defineArgument(CloudePottier3fDefinition, "cols", "int32");
defineArgument(CloudePottier3fDefinition, "t11", "single", "input", ["rows" "cols"]); 
defineArgument(CloudePottier3fDefinition, "t22", "single", "input", ["rows" "cols"]); 
defineArgument(CloudePottier3fDefinition, "t33", "single", "input", ["rows" "cols"]); 
defineArgument(CloudePottier3fDefinition, "t12r", "single", "input", ["rows" "cols"]); 
defineArgument(CloudePottier3fDefinition, "t13r", "single", "input", ["rows" "cols"]); 
defineArgument(CloudePottier3fDefinition, "t23r", "single", "input", ["rows" "cols"]); 
defineArgument(CloudePottier3fDefinition, "t12i", "single", "input", ["rows" "cols"]); 
defineArgument(CloudePottier3fDefinition, "t13i", "single", "input", ["rows" "cols"]); 
defineArgument(CloudePottier3fDefinition, "t23i", "single", "input", ["rows" "cols"]); 
defineArgument(CloudePottier3fDefinition, "outH", "single", "output", ["rows" "cols"]); 
defineArgument(CloudePottier3fDefinition, "outAlpha", "single", "output", ["rows" "cols"]); 
defineArgument(CloudePottier3fDefinition, "outA", "single", "output", ["rows" "cols"]); 
validate(CloudePottier3fDefinition);


CloudePottier3dDefinition = addFunction(libDef, ...
   "void CloudePottier3d(int rows,int cols,double const * t11,double const * t22,double const * t33,double const * t12r,double const * t13r,double const * t23r,double const * t12i,double const * t13i,double const * t23i,double * outH,double * outAlpha,double * outA)", ...
   "MATLABName", "clib.gars.CloudePottier3d", ...
   "Description", "clib.gars.CloudePottier3d Representation of C++ function CloudePottier3d.");
defineArgument(CloudePottier3dDefinition, "rows", "int32");
defineArgument(CloudePottier3dDefinition, "cols", "int32");
defineArgument(CloudePottier3dDefinition, "t11", "double", "input", ["rows" "cols"]);
defineArgument(CloudePottier3dDefinition, "t22", "double", "input", ["rows" "cols"]);
defineArgument(CloudePottier3dDefinition, "t33", "double", "input", ["rows" "cols"]);
defineArgument(CloudePottier3dDefinition, "t12r", "double", "input", ["rows" "cols"]);
defineArgument(CloudePottier3dDefinition, "t13r", "double", "input", ["rows" "cols"]);
defineArgument(CloudePottier3dDefinition, "t23r", "double", "input", ["rows" "cols"]);
defineArgument(CloudePottier3dDefinition, "t12i", "double", "input", ["rows" "cols"]);
defineArgument(CloudePottier3dDefinition, "t13i", "double", "input", ["rows" "cols"]);
defineArgument(CloudePottier3dDefinition, "t23i", "double", "input", ["rows" "cols"]);
defineArgument(CloudePottier3dDefinition, "outH", "double", "output", ["rows" "cols"]);
defineArgument(CloudePottier3dDefinition, "outAlpha", "double", "output", ["rows" "cols"]);
defineArgument(CloudePottier3dDefinition, "outA", "double", "output", ["rows" "cols"]);
validate(CloudePottier3dDefinition);


CloudePottier2fDefinition = addFunction(libDef, ...
   "void CloudePottier2f(int rows,int cols,float const * c11,float const * c22,float const * c12r,float const * c12i,float * outH,float * outAlpha,float * outA)", ...
   "MATLABName", "clib.gars.CloudePottier2f", ...
   "Description", "clib.gars.CloudePottier2f Representation of C++ function CloudePottier2f.");
defineArgument(CloudePottier2fDefinition, "rows", "int32");
defineArgument(CloudePottier2fDefinition, "cols", "int32");
defineArgument(CloudePottier2fDefinition, "c11", "single", "input", ["rows" "cols"]); 
defineArgument(CloudePottier2fDefinition, "c22", "single", "input", ["rows" "cols"]); 
defineArgument(CloudePottier2fDefinition, "c12r", "single", "input", ["rows" "cols"]); 
defineArgument(CloudePottier2fDefinition, "c12i", "single", "input", ["rows" "cols"]); 
defineArgument(CloudePottier2fDefinition, "outH", "single", "output", ["rows" "cols"]); 
defineArgument(CloudePottier2fDefinition, "outAlpha", "single", "output", ["rows" "cols"]); 
defineArgument(CloudePottier2fDefinition, "outA", "single", "output", ["rows" "cols"]); 
validate(CloudePottier2fDefinition);


CloudePottier2dDefinition = addFunction(libDef, ...
   "void CloudePottier2d(int rows,int cols,double const * c11,double const * c22,double const * c12r,double const * c12i,double * outH,double * outAlpha,double * outA)", ...
   "MATLABName", "clib.gars.CloudePottier2d", ...
   "Description", "clib.gars.CloudePottier2d Representation of C++ function CloudePottier2d.");
defineArgument(CloudePottier2dDefinition, "rows", "int32");
defineArgument(CloudePottier2dDefinition, "cols", "int32");
defineArgument(CloudePottier2dDefinition, "c11", "double", "input", ["rows" "cols"]);
defineArgument(CloudePottier2dDefinition, "c22", "double", "input", ["rows" "cols"]);
defineArgument(CloudePottier2dDefinition, "c12r", "double", "input", ["rows" "cols"]);
defineArgument(CloudePottier2dDefinition, "c12i", "double", "input", ["rows" "cols"]);
defineArgument(CloudePottier2dDefinition, "outH", "double", "output", ["rows" "cols"]);
defineArgument(CloudePottier2dDefinition, "outAlpha", "double", "output", ["rows" "cols"]);
defineArgument(CloudePottier2dDefinition, "outA", "double", "output", ["rows" "cols"]);
validate(CloudePottier2dDefinition);


YamaguchifDefinition = addFunction(libDef, ...
   "void Yamaguchif(int rows,int cols,float const * c11,float const * c22,float const * c33,float const * c12r,float const * c13r,float const * c23r,float const * c12i,float const * c13i,float const * c23i,float * outPs,float * outPd,float * outPv,float * outPh)", ...
   "MATLABName", "clib.gars.Yamaguchif", ...
   "Description", "clib.gars.Yamaguchif Representation of C++ function Yamaguchif.");
defineArgument(YamaguchifDefinition, "rows", "int32");
defineArgument(YamaguchifDefinition, "cols", "int32");
defineArgument(YamaguchifDefinition, "c11", "single", "input", ["rows" "cols"]); 
defineArgument(YamaguchifDefinition, "c22", "single", "input", ["rows" "cols"]); 
defineArgument(YamaguchifDefinition, "c33", "single", "input", ["rows" "cols"]); 
defineArgument(YamaguchifDefinition, "c12r", "single", "input", ["rows" "cols"]); 
defineArgument(YamaguchifDefinition, "c13r", "single", "input", ["rows" "cols"]); 
defineArgument(YamaguchifDefinition, "c23r", "single", "input", ["rows" "cols"]); 
defineArgument(YamaguchifDefinition, "c12i", "single", "input", ["rows" "cols"]); 
defineArgument(YamaguchifDefinition, "c13i", "single", "input", ["rows" "cols"]); 
defineArgument(YamaguchifDefinition, "c23i", "single", "input", ["rows" "cols"]); 
defineArgument(YamaguchifDefinition, "outPs", "single", "output", ["rows" "cols"]); 
defineArgument(YamaguchifDefinition, "outPd", "single", "output", ["rows" "cols"]); 
defineArgument(YamaguchifDefinition, "outPv", "single", "output", ["rows" "cols"]); 
defineArgument(YamaguchifDefinition, "outPh", "single", "output", ["rows" "cols"]); 
validate(YamaguchifDefinition);


YamaguchidDefinition = addFunction(libDef, ...
   "void Yamaguchid(int rows,int cols,double const * c11,double const * c22,double const * c33,double const * c12r,double const * c13r,double const * c23r,double const * c12i,double const * c13i,double const * c23i,double * outPs,double * outPd,double * outPv,double * outPh)", ...
   "MATLABName", "clib.gars.Yamaguchid", ...
   "Description", "clib.gars.Yamaguchid Representation of C++ function Yamaguchid.");
defineArgument(YamaguchidDefinition, "rows", "int32");
defineArgument(YamaguchidDefinition, "cols", "int32");
defineArgument(YamaguchidDefinition, "c11", "double", "input", ["rows" "cols"]);
defineArgument(YamaguchidDefinition, "c22", "double", "input", ["rows" "cols"]);
defineArgument(YamaguchidDefinition, "c33", "double", "input", ["rows" "cols"]);
defineArgument(YamaguchidDefinition, "c12r", "double", "input", ["rows" "cols"]);
defineArgument(YamaguchidDefinition, "c13r", "double", "input", ["rows" "cols"]);
defineArgument(YamaguchidDefinition, "c23r", "double", "input", ["rows" "cols"]);
defineArgument(YamaguchidDefinition, "c12i", "double", "input", ["rows" "cols"]);
defineArgument(YamaguchidDefinition, "c13i", "double", "input", ["rows" "cols"]);
defineArgument(YamaguchidDefinition, "c23i", "double", "input", ["rows" "cols"]);
defineArgument(YamaguchidDefinition, "outPs", "double", "output", ["rows" "cols"]);
defineArgument(YamaguchidDefinition, "outPd", "double", "output", ["rows" "cols"]);
defineArgument(YamaguchidDefinition, "outPv", "double", "output", ["rows" "cols"]);
defineArgument(YamaguchidDefinition, "outPh", "double", "output", ["rows" "cols"]);
validate(YamaguchidDefinition);


G4UfDefinition = addFunction(libDef, ...
   "int G4Uf(int rows,int cols,float const * t11,float const * t22,float const * t33,float const * t12r,float const * t13r,float const * t23r,float const * t12i,float const * t13i,float const * t23i,float * outPs,float * outPd,float * outPv,float * outPh)", ...
   "MATLABName", "clib.gars.G4Uf", ...
   "Description", "clib.gars.G4Uf Representation of C++ function G4Uf.");
defineArgument(G4UfDefinition, "rows", "int32");
defineArgument(G4UfDefinition, "cols", "int32");
defineArgument(G4UfDefinition, "t11", "single", "input", ["rows" "cols"]); 
defineArgument(G4UfDefinition, "t22", "single", "input", ["rows" "cols"]); 
defineArgument(G4UfDefinition, "t33", "single", "input", ["rows" "cols"]); 
defineArgument(G4UfDefinition, "t12r", "single", "input", ["rows" "cols"]); 
defineArgument(G4UfDefinition, "t13r", "single", "input", ["rows" "cols"]); 
defineArgument(G4UfDefinition, "t23r", "single", "input", ["rows" "cols"]); 
defineArgument(G4UfDefinition, "t12i", "single", "input", ["rows" "cols"]); 
defineArgument(G4UfDefinition, "t13i", "single", "input", ["rows" "cols"]); 
defineArgument(G4UfDefinition, "t23i", "single", "input", ["rows" "cols"]); 
defineArgument(G4UfDefinition, "outPs", "single", "output", ["rows" "cols"]); 
defineArgument(G4UfDefinition, "outPd", "single", "output", ["rows" "cols"]); 
defineArgument(G4UfDefinition, "outPv", "single", "output", ["rows" "cols"]); 
defineArgument(G4UfDefinition, "outPh", "single", "output", ["rows" "cols"]); 
defineOutput(G4UfDefinition, "RetVal", "int32");
validate(G4UfDefinition);


G4UdDefinition = addFunction(libDef, ...
   "int G4Ud(int rows,int cols,double const * t11,double const * t22,double const * t33,double const * t12r,double const * t13r,double const * t23r,double const * t12i,double const * t13i,double const * t23i,double * outPs,double * outPd,double * outPv,double * outPh)", ...
   "MATLABName", "clib.gars.G4Ud", ...
   "Description", "clib.gars.G4Ud Representation of C++ function G4Ud.");
defineArgument(G4UdDefinition, "rows", "int32");
defineArgument(G4UdDefinition, "cols", "int32");
defineArgument(G4UdDefinition, "t11", "double", "input", ["rows" "cols"]);
defineArgument(G4UdDefinition, "t22", "double", "input", ["rows" "cols"]);
defineArgument(G4UdDefinition, "t33", "double", "input", ["rows" "cols"]);
defineArgument(G4UdDefinition, "t12r", "double", "input", ["rows" "cols"]);
defineArgument(G4UdDefinition, "t13r", "double", "input", ["rows" "cols"]);
defineArgument(G4UdDefinition, "t23r", "double", "input", ["rows" "cols"]);
defineArgument(G4UdDefinition, "t12i", "double", "input", ["rows" "cols"]);
defineArgument(G4UdDefinition, "t13i", "double", "input", ["rows" "cols"]);
defineArgument(G4UdDefinition, "t23i", "double", "input", ["rows" "cols"]);
defineArgument(G4UdDefinition, "outPs", "double", "output", ["rows" "cols"]);
defineArgument(G4UdDefinition, "outPd", "double", "output", ["rows" "cols"]);
defineArgument(G4UdDefinition, "outPv", "double", "output", ["rows" "cols"]);
defineArgument(G4UdDefinition, "outPh", "double", "output", ["rows" "cols"]);
defineOutput(G4UdDefinition, "RetVal", "int32");
validate(G4UdDefinition);

validate(libDef);

end
