% mex_compile - 编译MEX库的脚本
%
% Author: Yinghao Hu
% Repository: https://github.com/Mothanburg/IPSART

source_path = '..\mex';

% 外部的Eigen和opencl sdk路径，根据自己的路径选填
eigen_path = '..\mex\thirdparty\eigen-5.0.0';
opencl_path = '..\mex\thirdparty\OpenCL-SDK-v2025.07.23-Win-x64';

% 将openclc内核代码复制到头文件中
cl_include = fullfile(source_path, 'include', 'autogen');
if ~exist(cl_include, 'dir')
    mkdir(cl_include);
end
src_dir = fullfile(source_path, 'opencl');
cl_files = dir(fullfile(src_dir, '*.cl'));
for i = 1:length(cl_files)
    src_path = fullfile(cl_files(i).folder, cl_files(i).name);
    [~,basename,~] = fileparts(src_path);
    filename = sprintf('%s.cl.h', basename);
    target_path = fullfile(cl_include, filename);
    fid = fopen(target_path, 'w');
    if fid ~= -1
        fprintf(fid, '// This file is automatically generated.\n');
        fprintf(fid, '// All changes in this file will be ignored when compiling.\n');
        fprintf(fid, '#pragma once\n');
        macro_name = upper(basename);
        fprintf(fid, '// content of ''%s''\n', cl_files(i).name);
        fprintf(fid, 'inline constexpr char SRC_%s[] = R"OPENCLC(\n', macro_name);
        content = fileread(src_path);
        fprintf(fid, '%s', content);
        fprintf(fid, '\n)OPENCLC";\n');
        fclose(fid);
    else
        error('unknown error occurred when creating the OpenCL source file of %s.', cl_files(i).name);
    end
end

% 编译器用的是Visual Studio，COMPFLAGS是MSVC格式的
mex('-v', ...
    '-R2018a', ...
    '-outdir', '..\bin', ...
    '-output', 'internal__mex_bridge', ...
    'COMPFLAGS="/utf-8 /std:c++latest /EHsc /bigobj /W3 /openmp"', ...
    '-DEIGEN_NO_DEBUG', ...
    strcat('-I', eigen_path), ...
    strcat('-I', opencl_path, '\include'), ...
    strcat('-I', source_path, '\include'), ...
    strcat('-L', opencl_path, '\lib'), ...
    "-lOpenCL", "-lOpenCLExt", "-lOpenCLUtils", "-lOpenCLUtilsCpp", ...
    fullfile(source_path, 'source', '*.cpp'));
