-- this file is only for intellisense, just for xmake config and generate compliation commands
add_rules("mode.release", "mode.debug")
set_defaultarchs("x64")
set_runtimes("MD")
set_warnings("all")

add_requires("opencl", "openmp")

target("IPSART")
    set_kind("shared")
    add_packages("opencl", "openmp")

    set_languages("c++23")
    add_includedirs("include", "thirdparty/eigen-5.0.0")
    add_includedirs("C:\\Program Files\\MATLAB\\R2024a\\extern\\include") -- subsitute to your MATLAB path
    add_files("source/*.cpp")

    -- Enable necessary flags for MSVC
    add_cxxflags(
        "cl::/bigobj",
        "cl::/D_SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING"
        )

    -- copy OpenCL source files to the include directory as header files
    on_config(function (target)
        local cl_include = path.join("include", "autogen")
        if not os.isdir(cl_include) then
            os.mkdir(cl_include)
        end
        for _, src_path in ipairs(os.files(path.join(os.projectdir(), "opencl", "*.cl"))) do
            local filename = format("%s.cl.h", path.basename(src_path))
            local file = io.open(path.join(cl_include, filename), "w")
            if file then
                file:print("// This file is automatically generated by the \"config\" script.")
                file:print("// All changes in this file will be ignored when compiling.")
                file:print(format("#ifndef CL_SOURCE_%s", string.upper(path.basename(src_path))))
                file:print(format("#define CL_SOURCE_%s", string.upper(path.basename(src_path))))
                file:print(format("// content of '%s'", path.filename(src_path)))
                file:print(format("inline constexpr auto SRC_%s = R\"OPENCLC(", string.upper(path.basename(src_path))))
                local content = io.readfile(src_path)
                file:print(content)
                file:print(")OPENCLC\";")
                file:print("#endif")
                file:close()
            else
                raise(format("unknown error occurred when creating the OpenCL source file of %s.", path.filename(src_path)))
            end
        end
    end)

