import("core.project.config")

-- install GaRS native library
function main(target)
        if not is_mode("release", "releasedbg", "minsizerel") then
            local curmode = get_config("mode")
            raise("please change mode '%s' to a kind of release mode.", curmode)
        end

        local installdir = path.join("..", "matlab", "bin")
        installdir = path.absolute(installdir, os.projectdir())
        if not os.exists(installdir) then
            os.mkdir(installdir)
        end

        -- install all shared libs of depended packages
        local installed = {}
        for _, pkg in ipairs(target:orderpkgs()) do
            if pkg:enabled() then
                for _, libpath in ipairs(table.wrap(pkg:get("libfiles"))) do
                    if _is_shared_lib(target, libpath) then
                        local libname = path.filename(libpath)
                        if installed[libname] then
                            wprint("'%s' already exists, overwriting it.", libname)
                        end
                        os.cp(libpath, installdir)
                        installed[libname] = true
                    end
                end
            end
        end

        -- install GaRS library file
        local tgt_file = target:targetfile()
        os.cp(tgt_file, installdir)

        print("You need to run the generated script to generate matlab interface for GaRS.")
        _gen_matlab_interface_generator(target, installdir)
end

function _is_shared_lib(target, libpath)
    if target:is_plat("windows") then
        return libpath:endswith(".dll")
    else -- plat == "linux" or plat == "macosx" or any else
        return libpath:endswith(".so") or libpath:match(".+%.so%..+$") or libpath:endswith(".dylib")
    end
end

function _gen_matlab_interface_generator(target, installdir)
    local file = io.open("autogen_publishMatlabInterface.m", "w")
    if file then
        local header_file = path.join(os.projectdir(), "include", "GaRS.h")
        local tgt_file = path.join(os.projectdir(), target:targetfile())
        if target:is_plat("windows") then
            tgt_file = string.gsub(tgt_file, "%.dll", ".lib")
        end
        file:print("% This file is automatically generated by the install script")
        file:print("% Before building matlab interface, you should run `mex -setup cpp` ")
        file:print("% and select the SAME compiler as the one you build GaRS.")
        file:print("")
        file:print("%%%% You must run this part first.")
        file:print(format("header = \"%s\";", header_file))
        file:print(format("lib = \"%s\";", tgt_file))
        file:print("clibgen.generateLibraryDefinition(...")
        file:print("    header, ...")
        file:print("    Libraries=lib, ...")
        file:print("    PackageName=\"gars\", ...")
        file:print("    CLinkage=true, ...")
        file:print(format("    OutputFolder=\"%s\", ...", path.join(os.projectdir(), config:buildir())))
        file:print("    OverwriteExistingDefinitionFiles=true, ...")
        file:print("    Verbose=true ...")
        file:print(");")
        file:print("% Please Edit the define script by the instructions in the file.")
        file:print("edit(fullfile(\"build\", \"definegars.m\"));")
        file:print("%%%% Then you should run this part.")
        file:print(format("addpath(\"%s\");", path.join(os.projectdir(), config:buildir())))
        file:print("build(definegars());")
        file:print(format("copyfile(fullfile(\"%s\", \"gars\", \"garsInterface.dll\"), \"%s\");", path.join(os.projectdir(), config:buildir()), installdir))
        file:print("rehash(\"path\");")

        file:close()
    else
        raise("unknown error occurred when creating the matlab file.")
    end
end