-- copy opencl sources to cpp const char*
function main(target)

        local cl_include = path.join(target:autogendir(), "opencl")
        if not os.isdir(cl_include) then
            os.mkdir(cl_include)
        end

        target:add("includedirs", cl_include)

        for _, src_path in ipairs(os.files(path.join(os.projectdir(), "src.opencl", "*.cl"))) do
            local filename = format("%s.src.h", path.basename(src_path))

            local file = io.open(path.join(cl_include, filename), "w")
            if file then
                file:print("// This file is automatically generated by the \"on_config\" script.")
                file:print("// All changes in this file will be ignored when compiling.")
                file:print(format("#ifndef CL_SOURCE_%s", string.upper(path.basename(src_path))))
                file:print(format("#define CL_SOURCE_%s", string.upper(path.basename(src_path))))

                file:print(format("// content of '%s'", path.filename(src_path)))
                file:print(format("inline constexpr auto src_%s = R\"OPENCLC(", path.basename(src_path)))
                local content = io.readfile(src_path)
                file:print(content)
                file:print(")OPENCLC\";")

                file:print("#endif")
                file:close()
            else
                raise(format("unknown error occurred when creating the OpenCL source file of %s.", path.filename(src_path)))
            end
        end

end
