// This file is automatically generated.
// All changes in this file will be ignored when compiling.
#pragma once
// content of 'RefinedLeeFilter.cl'
inline constexpr auto SRC_REFINEDLEEFILTER = R"OPENCLC(
// Convention: Leading dimension is dim 0, and data storage is col-major
#ifdef ENABLE_FP64
#pragma OPENCL EXTENSION cl_khr_fp64 : enable
#define dtype double
#else
#define dtype float
#endif

__kernel void
#ifdef MAT_SIZE_3X3
span_calc(__global dtype *span,
          __global const dtype *c11,
          __global const dtype *c22,
          __global const dtype *c33)
#else
span_calc(__global dtype *span,
          __global const dtype *c11,
          __global const dtype *c22)
#endif
{
    int idx = get_global_id(0) * get_global_size(1) + get_global_id(1);
#ifdef MAT_SIZE_3X3
    span[idx] = c11[idx] + c22[idx] + c33[idx];
#else
    span[idx] = c11[idx] + c22[idx];
#endif
}

// A 7x7 refined lee filter
__kernel void
page_filting(int rows, int cols,
             __global const dtype *span,  // the SPAN of the PolSAR image
             int shared_rows, int shared_cols, __local dtype *shared_mem,
             __constant dtype *prewitt,   // the size of prewitt operator templates is 7x7x8
             int look_num,                // look number
             __global const dtype *input, // input Cij to be filted
             __global dtype *output)
{
    int wg_row = get_group_id(0);
    int wg_col = get_group_id(1);
    int enqd_wg_rows = get_enqueued_local_size(0);
    int enqd_wg_cols = get_enqueued_local_size(1);
    int wg_rows = get_local_size(0);
    int wg_cols = get_local_size(1);
    int local_row = get_local_id(0);
    int local_col = get_local_id(1);
    int shared_mem_page_offset = shared_rows * shared_cols;
    for (int c = local_col; c < shared_cols; c += wg_cols)
    {
        for (int r = local_row; r < shared_rows; r += wg_rows)
        {
            int row = min(max(wg_row * enqd_wg_rows + r - 3, 0), rows - 1);
            int col = min(max(wg_col * enqd_wg_cols + c - 3, 0), cols - 1);
            shared_mem[c * shared_rows + r] = span[col * rows + row];
            shared_mem[c * shared_rows + r + shared_mem_page_offset] = input[col * rows + row];
        }
    }

    work_group_barrier(CLK_LOCAL_MEM_FENCE);

    dtype mean_mat[9] = {0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
    __attribute__((opencl_unroll_hint)) for (int j = 0; j < 3; j++)
    {
        __attribute__((opencl_unroll_hint)) for (int i = 0; i < 3; i++)
        {
            __attribute__((opencl_unroll_hint)) for (int dc = 0; dc < 3; dc++)
            {
                __attribute__((opencl_unroll_hint)) for (int dr = 0; dr < 3; dr++)
                {
                    int lr = local_row + i * 2 + dr;
                    int lc = local_col + j * 2 + dc;
                    mean_mat[j * 3 + i] += shared_mem[lc * shared_rows + lr];
                }
            }
        }
    }

    // Calculate Prewitt id

    // window id
    dtype sums[4];
    sums[0] = fabs(mean_mat[2] + mean_mat[5] + mean_mat[8] - mean_mat[0] - mean_mat[3] - mean_mat[6]); 
    sums[1] = fabs(mean_mat[1] + mean_mat[2] + mean_mat[5] - mean_mat[3] - mean_mat[6] - mean_mat[7]);
    sums[2] = fabs(mean_mat[0] + mean_mat[1] + mean_mat[2] - mean_mat[6] - mean_mat[7] - mean_mat[8]);
    sums[3] = fabs(mean_mat[0] + mean_mat[1] + mean_mat[3] - mean_mat[5] - mean_mat[7] - mean_mat[8]);

    int window_id = 0;
    __attribute__((opencl_unroll_hint)) for (int i = 1; i < 4; i++)
    {
        window_id += isless(sums[window_id], sums[i]) * (i - window_id);
    }

    dtype distance[8];
    distance[0] = fabs(mean_mat[5] - mean_mat[4]); // m23 - m22
    distance[1] = fabs(mean_mat[2] - mean_mat[4]); // m13 - m22
    distance[2] = fabs(mean_mat[1] - mean_mat[4]); // m12 - m22
    distance[3] = fabs(mean_mat[0] - mean_mat[4]); // m11 - m22
    distance[4] = fabs(mean_mat[3] - mean_mat[4]); // m21 - m22
    distance[5] = fabs(mean_mat[6] - mean_mat[4]); // m31 - m22
    distance[6] = fabs(mean_mat[7] - mean_mat[4]); // m32 - m22
    distance[7] = fabs(mean_mat[8] - mean_mat[4]); // m33 - m22

    int prewitt_id = isgreater(distance[window_id], distance[window_id + 4]) * 4 + window_id;

    dtype z_mean = 0.0;
    __attribute__((opencl_unroll_hint)) for (int j = 0; j < 7; j++)
    {
        __attribute__((opencl_unroll_hint)) for (int i = 0; i < 7; i++)
        {
            z_mean += shared_mem[(local_col + j) * shared_rows + local_row + i] *
                      prewitt[49 * prewitt_id + j * 7 + i];
        }
    }
    z_mean /= 28.0;

    dtype z_var = 0.0;
    __attribute__((opencl_unroll_hint)) for (int j = 0; j < 7; j++)
    {
        __attribute__((opencl_unroll_hint)) for (int i = 0; i < 7; i++)
        {
            dtype z = shared_mem[(local_col + j) * shared_rows + local_row + i] *
                      prewitt[49 * prewitt_id + j * 7 + i];
            z_var += (z - z_mean) * (z - z_mean);
        }
    }
    z_var /= 28.0;

    dtype v_var = 1.0 / look_num;
    dtype x_var = (z_var - z_mean * z_mean * v_var) / (1.0 + v_var);
    dtype factor = (x_var + 1e-30) / (z_var + 1e-30); // avoid nan
    factor = min(0.0, max(factor, 1.0));

    dtype mean_input = 0.0;
    __attribute__((opencl_unroll_hint)) for (int j = 0; j < 7; j++)
    {
        __attribute__((opencl_unroll_hint)) for (int i = 0; i < 7; i++)
        {
            mean_input += shared_mem[(local_col + j) * shared_rows + local_row + i + shared_mem_page_offset] *
                          prewitt[49 * prewitt_id + j * 7 + i];
        }
    }
    mean_input /= 28.0;

    int g_row = get_global_id(0);
    int g_col = get_global_id(1);
    output[g_col * rows + g_row] = mean_input +
                                   factor * (shared_mem[(local_col + 3) * shared_rows + local_row + 3 + shared_mem_page_offset] - mean_input);
}
)OPENCLC";
